[package]
name = "yaml_test_runner"
version = "7.6.1-alpha.1"
edition = "2018"
authors = ["Elastic and Contributors"]
description = "Generates and runs tests from Elasticsearch's YAML test specs"
repository = "https://github.com/elastic/elasticsearch-rs"

[dependencies]
elasticsearch = { version = "7.6.1-alpha.1", path = "../elasticsearch" }
api_generator = { version = "7.6.1-alpha.1", path = "../api_generator" }

clap = "~2"
failure = "0.1.6"
itertools = "0.8.2"
Inflector = "0.11.4"
lazy_static = "1.4.0"
quote = "~0.3"
regex = "1.3.1"
reqwest = "~0.9"
serde = "~1"
serde_yaml = "0.8.11"
serde_json = "~1"
syn = { version = "~0.11", features = ["full"] }
sysinfo = "0.9.6"
url = "2.1.1"
yaml-rust = "0.4.3"

[dev-dependencies]
tokio = { version = "0.2.0", default-features = false, features = ["macros", "tcp", "time"] }
